#!/usr/bin/env python3
"""
build-blog.py — Generate /blog index + /blog/[slug] dynamic route + initial article
stubs. Articles are sourced from intake.topics (or research topical-map.md), each
with a unique target keyword cluster.

Generic. Outputs:
  - src/app/blog/page.tsx          (article index, Stitch-styled)
  - src/app/blog/[slug]/page.tsx   (dynamic article view)
  - src/app/blog/articles.ts       (article metadata + bodies)

Usage:
  build-blog.py --project <path> --intake <intake.json>
"""
import argparse
import json
import re
import sys
from pathlib import Path



def slugify(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--project", required=True)
    ap.add_argument("--intake", required=True)
    args = ap.parse_args()

    project = Path(args.project).resolve()
    intake = json.loads(Path(args.intake).read_text())

    business = intake.get("businessName", "")
    industry = intake.get("industry", "")
    topics = intake.get("topics", []) or []
    services = intake.get("services", []) or []
    primary_kws = intake.get("primaryKeywords", []) or []

    if not topics:
        # Fall back to first 3 services + first 2 keywords
        topics = services[:3] + primary_kws[:2]
    if not topics:
        topics = ["Why Hire a Pro", "Materials Guide", "Maintenance Tips"]

    # Generate article stubs from topics (max 6 to start)
    articles = []
    for topic in topics[:6]:
        title = topic if topic[0].isupper() else topic.title()
        slug = slugify(title)
        keyword = topic
        articles.append({
            "slug": slug,
            "title": title,
            "excerpt": f"Everything {business} customers need to know about {topic}.",
            "keyword": keyword,
            "body": (
                f"# {title}\n\n"
                f"At {business}, our team has fielded countless questions about {topic}. "
                f"This guide walks you through what you need to know — drawn from real "
                f"projects we've completed across the {intake.get('geographicScope', 'region')}.\n\n"
                f"## What is {topic}?\n\n"
                f"Understanding {topic} starts with the basics. Whether you're planning "
                f"a new project or maintaining an existing one, knowing the fundamentals "
                f"helps you make better decisions and get more value out of every dollar.\n\n"
                f"## Why it matters for {industry}\n\n"
                f"In our region, the climate, building codes, and homeowner expectations "
                f"create unique requirements. {business} brings 15+ years of local "
                f"experience to every project.\n\n"
                f"## Get expert guidance\n\n"
                f"Have questions? Call us at {intake.get('phone', '')} or "
                f"[request a free quote](/contact)."
            ),
        })

    blog_dir = project / "src" / "app" / "blog"
    blog_dir.mkdir(parents=True, exist_ok=True)
    (blog_dir / "[slug]").mkdir(exist_ok=True)

    # articles.ts — metadata module
    articles_ts = "// Generated by build-blog.py — auto-regenerated each build.\n"
    articles_ts += "export type Article = { slug: string; title: string; excerpt: string; keyword: string; body: string; };\n"
    articles_ts += f"export const articles: Article[] = {json.dumps(articles, indent=2)};\n"
    (blog_dir / "articles.ts").write_text(articles_ts)

    # Index page — clones home page's chrome (top banner + navbar + footer) so the
    # blog inherits the Stitch design including the logo + Services dropdown.
    home_tsx = (project / "src" / "app" / "page.tsx").read_text()

    def balanced_extract(text: str, tag: str, open_pattern: str) -> str:
        """Find <tag ...> matching open_pattern and return the full balanced element."""
        m = re.search(open_pattern, text)
        if not m:
            return ""
        start = m.start()
        depth = 1
        pos = m.end()
        n = len(text)
        open_re = re.compile(rf"<{tag}\b")
        close_re = re.compile(rf"</{tag}>")
        while pos < n and depth > 0:
            no = open_re.search(text, pos)
            nc = close_re.search(text, pos)
            if not nc:
                return ""
            if no and no.start() < nc.start():
                depth += 1
                pos = no.end()
            else:
                depth -= 1
                pos = nc.end()
        return text[start:pos] if depth == 0 else ""

    # Top phone-banner: <div className="bg-primary ... sticky top-0 ...">
    banner = balanced_extract(
        home_tsx,
        "div",
        r'<div\s+className="[^"]*\bbg-primary\b[^"]*\bsticky\s+top-0[^"]*"[^>]*>',
    )

    # Navbar: the full <header>...</header>
    navbar = balanced_extract(home_tsx, "header", r"<header\b[^>]*>")

    # Footer: <footer ...>...</footer>
    footer = balanced_extract(home_tsx, "footer", r"<footer\b[^>]*>")

    index_tsx = '''// Generated by build-blog.py
import Link from "next/link";
import { articles } from "./articles";

export default function BlogIndex() {
  return (
    <div className="bg-background text-on-background">
''' + banner + "\n" + navbar + '''
      <main className="py-24 bg-surface-dim">
        <div className="max-w-[1280px] mx-auto px-6">
          <div className="text-center mb-16">
            <span className="text-primary font-bold text-sm uppercase tracking-[0.3em] block mb-3">Articles</span>
            <h1 className="font-h1-hero text-h1-hero text-on-background">''' + f"{business} Insights" + '''</h1>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {articles.map((a) => (
              <Link key={a.slug} href={`/blog/${a.slug}`} className="group glass p-8 rounded-[2rem] hover-lift transition-all">
                <h3 className="font-h3-card text-h3-card mb-3 group-hover:text-primary transition-colors">{a.title}</h3>
                <p className="font-body-md text-body-md text-secondary leading-relaxed mb-4">{a.excerpt}</p>
                <span className="text-primary font-bold text-sm uppercase tracking-wider">Read more &rarr;</span>
              </Link>
            ))}
          </div>
        </div>
      </main>
''' + footer + '''
    </div>
  );
}
'''
    (blog_dir / "page.tsx").write_text(index_tsx)

    # Dynamic article route
    article_tsx = '''// Generated by build-blog.py
import { articles } from "../articles";
import { notFound } from "next/navigation";
import Link from "next/link";

export function generateStaticParams() {
  return articles.map((a) => ({ slug: a.slug }));
}

export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const article = articles.find((a) => a.slug === slug);
  if (!article) notFound();
  const paragraphs = article.body.split("\\n\\n").map((p, i) => {
    if (p.startsWith("# ")) return <h1 key={i} className="font-h1-hero text-h1-hero mb-6">{p.slice(2)}</h1>;
    if (p.startsWith("## ")) return <h2 key={i} className="font-h2-section text-h2-section mt-12 mb-4">{p.slice(3)}</h2>;
    return <p key={i} className="font-body-md text-body-md text-secondary mb-6 leading-relaxed">{p}</p>;
  });
  return (
    <div className="bg-background text-on-background">
      <article className="max-w-3xl mx-auto px-6 py-24">
        {paragraphs}
        <div className="mt-12 pt-8 border-t border-slate-200">
          <Link href="/blog" className="text-primary font-bold text-sm uppercase tracking-wider">&larr; Back to all articles</Link>
        </div>
      </article>
    </div>
  );
}
'''
    (blog_dir / "[slug]" / "page.tsx").write_text(article_tsx)

    print(json.dumps({
        "ok": True,
        "articles_generated": len(articles),
        "slugs": [a["slug"] for a in articles],
        "files": [
            "src/app/blog/page.tsx",
            "src/app/blog/[slug]/page.tsx",
            "src/app/blog/articles.ts",
        ],
    }, indent=2))


if __name__ == "__main__":
    main()
