#!/usr/bin/env python3
"""
build-legal-pages.py — Generate /privacy and /terms pages from intake values.

Idempotent: skips pages that already exist. Generates minimal, accurate static
pages branded with the client's businessName, address, phone, email. Pages
inherit the site's chrome (navbar/footer) by reusing the home page's banner
+ navbar + footer markup so they look native to the site.

Usage:
  build-legal-pages.py --project <project-root> --intake <intake.json>
"""
import argparse
import json
import re
from datetime import date
from pathlib import Path


def extract_chrome(home_page_tsx: str) -> tuple[str, str]:
    """Extract banner+navbar (top chrome) and footer (bottom chrome) from the
    home page.tsx so legal pages can reuse them. Returns (top_chrome, footer)
    as JSX strings. If extraction fails, returns ('', '')."""
    # Top chrome: from start of return body up to and including the closing
    # </header> of the navbar.
    top_match = re.search(
        r'return\s*\(\s*\n?\s*<div[^>]*>\s*\n?(.*?</header>)',
        home_page_tsx,
        re.DOTALL,
    )
    top = top_match.group(1) if top_match else ""

    # Footer: <footer ...>...</footer>
    foot_match = re.search(r'(<footer[^>]*>.*?</footer>)', home_page_tsx, re.DOTALL)
    foot = foot_match.group(1) if foot_match else ""

    return top, foot


def build_privacy_jsx(intake: dict, top: str, footer: str) -> str:
    biz = (intake.get("businessName") or "Our Company").strip()
    email = (intake.get("email") or "").strip()
    phone = (intake.get("phone") or "").strip()
    addr = (intake.get("address") or "").strip()
    today = date.today().strftime("%B %d, %Y")

    contact_lines = []
    if email: contact_lines.append(f'<li>Email: <a href="mailto:{email}" className="text-primary hover:underline">{email}</a></li>')
    if phone: contact_lines.append(f'<li>Phone: <a href="tel:{re.sub(r"[^0-9+]","",phone)}" className="text-primary hover:underline">{phone}</a></li>')
    if addr:  contact_lines.append(f'<li>Address: {addr}</li>')
    contact_html = "\n            ".join(contact_lines) if contact_lines else "<li>See Contact page</li>"

    body = f'''<main className="min-h-screen bg-background text-on-background">
      <div className="max-w-4xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-extrabold text-slate-900 mb-2">Privacy Policy</h1>
        <p className="text-sm text-slate-500 mb-10">Last updated: {today}</p>

        <section className="prose prose-slate max-w-none mb-8">
          <p>{biz} (“we,” “our,” “us”) respects your privacy. This policy explains what information we collect, how we use it, and your rights.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-slate-900 mb-3">Information We Collect</h2>
          <ul className="list-disc pl-6 space-y-2 text-slate-700">
            <li>Information you provide via contact forms (name, email, phone, project details)</li>
            <li>Communications you send us (email, voicemail, chat)</li>
            <li>Anonymous analytics data (page views, referrer, browser type)</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-slate-900 mb-3">How We Use It</h2>
          <ul className="list-disc pl-6 space-y-2 text-slate-700">
            <li>To respond to your inquiry or estimate request</li>
            <li>To schedule and complete services you’ve requested</li>
            <li>To send service-related updates (no marketing email without consent)</li>
            <li>To improve our website and services</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-slate-900 mb-3">Sharing</h2>
          <p className="text-slate-700">We do not sell your personal information. We share it only with service providers required to operate (e.g. payment processors, scheduling tools) under confidentiality obligations, or when required by law.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-slate-900 mb-3">Your Rights</h2>
          <p className="text-slate-700">You can request access to, correction of, or deletion of personal information we hold about you at any time. Contact us using the information below.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-slate-900 mb-3">Contact</h2>
          <ul className="list-disc pl-6 space-y-2 text-slate-700">
            {contact_html}
          </ul>
        </section>
      </div>
    </main>'''

    return f'''// Generated by build-legal-pages.py.

export const metadata = {{
  title: "Privacy Policy — {biz}",
  description: "Privacy policy for {biz}.",
}};

export default function Page() {{
  return (
    <div className="bg-background text-on-background">
{top}
{body}
{footer}
    </div>
  );
}}
'''


def build_terms_jsx(intake: dict, top: str, footer: str) -> str:
    biz = (intake.get("businessName") or "Our Company").strip()
    email = (intake.get("email") or "").strip()
    addr = (intake.get("address") or "").strip()
    today = date.today().strftime("%B %d, %Y")

    body = f'''<main className="min-h-screen bg-background text-on-background">
      <div className="max-w-4xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-extrabold text-slate-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-slate-500 mb-10">Last updated: {today}</p>

        <section className="prose prose-slate max-w-none mb-8">
          <p>By using this website or engaging {biz} for services, you agree to these terms.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-slate-900 mb-3">Estimates and Quotes</h2>
          <p className="text-slate-700">All estimates are provided in good faith based on information available at the time. Final pricing depends on site conditions, materials selected, and any change orders agreed to during the project.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-slate-900 mb-3">Service Agreement</h2>
          <p className="text-slate-700">Work begins only after a signed agreement and any required deposit. Cancellations made in writing prior to materials being ordered will be refunded less any costs already incurred.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-slate-900 mb-3">Warranty</h2>
          <p className="text-slate-700">Workmanship warranty terms are spelled out in your project agreement. Material warranties are governed by the manufacturer.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-slate-900 mb-3">Limitation of Liability</h2>
          <p className="text-slate-700">To the fullest extent allowed by law, our liability is limited to the amount you paid us for the specific service in question. We are not liable for incidental or consequential damages.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-slate-900 mb-3">Website Use</h2>
          <p className="text-slate-700">Content on this website is provided for general information. We do not guarantee accuracy and reserve the right to update content at any time.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-slate-900 mb-3">Governing Law</h2>
          <p className="text-slate-700">These terms are governed by the laws of the state in which {biz} primarily operates{f' ({addr.split(",")[-2].strip()})' if addr and "," in addr else ""}.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-slate-900 mb-3">Contact</h2>
          <p className="text-slate-700">{f'Questions about these terms: <a href="mailto:{email}" className="text-primary hover:underline">{email}</a>' if email else 'Use our Contact page to reach us.'}</p>
        </section>
      </div>
    </main>'''

    return f'''// Generated by build-legal-pages.py.

export const metadata = {{
  title: "Terms of Service — {biz}",
  description: "Terms of service for {biz}.",
}};

export default function Page() {{
  return (
    <div className="bg-background text-on-background">
{top}
{body}
{footer}
    </div>
  );
}}
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--project", required=True)
    ap.add_argument("--intake", required=True)
    args = ap.parse_args()

    project = Path(args.project).resolve()
    intake = json.loads(Path(args.intake).read_text())

    home_path = project / "src" / "app" / "page.tsx"
    home_text = home_path.read_text() if home_path.exists() else ""
    top, footer = extract_chrome(home_text)

    privacy_dir = project / "src" / "app" / "privacy"
    terms_dir = project / "src" / "app" / "terms"

    report = {"privacy_built": False, "terms_built": False, "skipped": []}

    if not (privacy_dir / "page.tsx").exists():
        privacy_dir.mkdir(parents=True, exist_ok=True)
        (privacy_dir / "page.tsx").write_text(build_privacy_jsx(intake, top, footer))
        report["privacy_built"] = True
    else:
        report["skipped"].append("privacy")

    if not (terms_dir / "page.tsx").exists():
        terms_dir.mkdir(parents=True, exist_ok=True)
        (terms_dir / "page.tsx").write_text(build_terms_jsx(intake, top, footer))
        report["terms_built"] = True
    else:
        report["skipped"].append("terms")

    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
